### ISSUE TITLE
Mac os catalina 10.15.4, The application “nostlan” can’t be opened.

### ISSUE THREAD

**Issue by emolr** [quinton-ashley/nostlan#19]
Hi, i just found Nostlan, 
It sounds very cool! 

After downloading and unzipping the latest and second latest release I'm met with 'The application “nostlan” can’t be opened.' when trying to open it. 

Don't know if just my system, but it's not a message i've met before on this system.

Again, really cool project!

**Comment by quinton-ashley** [comment]
https://support.apple.com/guide/mac-help/open-a-mac-app-from-an-unidentified-developer-mh40616/mac

**Comment by emolr** [comment]
Hi @quinton-ashley

Thanks for getting back, I'm afraid it isn't enough. 
It isn't the usual problem with unidentified developer, so right click open doesn't make any difference I'm afraid.

<img width="636" alt="Screenshot 2020-06-07 at 13 55 46" src="https://user-images.githubusercontent.com/2789549/83968059-ba407980-a8c6-11ea-8051-022cb29b0044.png">

**Comment by emolr** [comment]
Hi again, 

I tried `chmod +x ~path/to/nostlan.app/Contents/MacOS/*`

It got the app to show the message you referred to, but then It chrashed, here's the output :) 

```
Process:               nostlan [37259]
Path:                  /private/var/folders/*/nostlan.app/Contents/MacOS/nostlan
Identifier:            com.qashto.nostlan
Version:               1.10.3 (1.10.3)
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           nostlan [37259]
User ID:               501

Date/Time:             2020-06-08 08:00:47.097 +0200
OS Version:            Mac OS X 10.15.4 (19E287)
Report Version:        12
Bridge OS Version:     4.4 (17P4281)
Anonymous UUID:        4E868507-AA4A-0EAE-1D0B-A75E4201B582

Sleep/Wake UUID:       3D2127B3-4168-48A2-AA52-34971EC8590C

Time Awake Since Boot: 10000 seconds
Time Since Wake:       3400 seconds

System Integrity Protection: enabled

Notes:                 Translocated Process

Crashed Thread:        0

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    DYLD, [0x1] Library missing

Application Specific Information:
dyld: launch, loading dependent libraries

Dyld Error Message:
  Library not loaded: @rpath/Electron Framework.framework/Electron Framework
  Referenced from: /private/var/folders/*/nostlan.app/Contents/MacOS/nostlan
  Reason: no suitable image found.  Did find:
	/private/var/folders/fq/dzktjj7d5yngm1b2p82008vm0000gn/T/AppTranslocation/CD4BA03F-4693-4194-A361-ABE176F965A9/d/nostlan.app/Contents/MacOS/../Frameworks/Electron Framework.framework/Electron Framework: file too short
	/private/var/folders/fq/dzktjj7d5yngm1b2p82008vm0000gn/T/AppTranslocation/CD4BA03F-4693-4194-A361-ABE176F965A9/d/nostlan.app/Contents/MacOS/../Frameworks/Electron Framework.framework/Electron Framework: stat() failed with errno=1

Binary Images:
       0x100a71000 -        0x100a99ff3 +com.qashto.nostlan (1.10.3 - 1.10.3) <596191EB-2C06-339C-917C-D986342C029E> /var/folders/*/nostlan.app/Contents/MacOS/nostlan
       0x107f43000 -        0x107fd4eff  dyld (750.5) <1F893B81-89A5-3502-8510-95B97B9F730D> /usr/lib/dyld
    0x7fff36cd5000 -     0x7fff36d8cff1  com.apple.MediaPlayer (1.0 - 1.0) <74DF946F-09C6-3053-BED6-EB83374261AE> /System/Library/Frameworks/MediaPlayer.framework/Versions/A/MediaPlayer

Model: MacBookPro15,3, BootROM 1037.100.362.0.0 (iBridge: 17.16.14281.0.0,0), 8 processors, 8-Core Intel Core i9, 2,3 GHz, 16 GB, SMC 
Graphics: kHW_IntelUHDGraphics630Item, Intel UHD Graphics 630, spdisplays_builtin
Graphics: kHW_AMDRadeonProVega20Item, Radeon Pro Vega 20, spdisplays_pcie_device, 4 GB
Memory Module: BANK 0/ChannelA-DIMM0, 8 GB, DDR4, 2400 MHz, SK Hynix, -
Memory Module: BANK 2/ChannelB-DIMM0, 8 GB, DDR4, 2400 MHz, SK Hynix, -
AirPort: spairport_wireless_card_type_airport_extreme (0x14E4, 0x7BF), wl0: Feb 28 2020 15:24:56 version 9.30.357.35.32.5.47 FWID 01-9ce4adf3
Bluetooth: Version 7.0.4f6, 3 services, 27 devices, 1 incoming serial ports
Network Service: Wi-Fi, AirPort, en0
USB Device: USB 3.1 Bus
USB Device: Apple T2 Bus
USB Device: Touch Bar Backlight
USB Device: Touch Bar Display
USB Device: Apple Internal Keyboard / Trackpad
USB Device: Headset
USB Device: Ambient Light Sensor
USB Device: FaceTime HD Camera (Built-in)
USB Device: Apple T2 Controller
Thunderbolt Bus: MacBook Pro, Apple Inc., 47.4
Thunderbolt Bus: MacBook Pro, Apple Inc., 47.4
```

<img width="999" alt="Screenshot 2020-06-08 at 08 04 51" src="https://user-images.githubusercontent.com/2789549/83997481-c37d2500-a95e-11ea-96af-85b4734d85ea.png">

I hope it's helpfull :)

**Comment by rvega-arg** [comment]
This issue is still present. Like @emolr said this is not an issue related to "unidentified developer"

**Comment by quinton-ashley** [comment]
I think I fixed the issue. Try the latest release! v1.11.0

**Comment by rvega-arg** [comment]
I'm still having the same issue. There is any way i can provide you with more info related to the error? I'm using macOS Catalina 10.15.5

**Comment by quinton-ashley** [comment]
v1.11.0 works fine on macOS Catalina 10.15.5 for me.  I'm not sure what is wrong with it.

**Comment by quinton-ashley** [comment]
I think I've figured it out. Testing it on my other mac now.

**Comment by quinton-ashley** [comment]
After I tested it on a mac not linked with my Apple Dev ID it says "This application can't be tested for malicious software and must be updated. Contact the developer."

Thank you for bringing this issue to my attention.  I will try to fix it ASAP.

**Comment by quinton-ashley** [comment]
Okay now I think I fixed it, please try again.  Thanks for bringing the issue to my attention.

**Comment by rvega-arg** [comment]
It is working now. Thanks!

**Comment by quinton-ashley** [comment]
Sweet!
